import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/authcontext/authContext'
import { RestaurantDataProvider } from '@/authcontext/RestaurantDataContext.js'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'gokidogo',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <RestaurantDataProvider>
          <body className={inter.className}>{children}</body>
        </RestaurantDataProvider>
      </AuthProvider>
    </html>
  )
}
